services:
  api:
    image: samuelnavd/music-service
    ports:
      - "443:8080"
    volumes:
      - /keystore/keystore.p12:/etc/letsencrypt/live/music.diezproyectos.com/keystore.p12
      - /data:/home/ubuntu/apiData